# Generated by Django 4.1.2 on 2022-10-30 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("custom_auth", "0004_alter_profile_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attraction",
            fields=[
                (
                    "uuid",
                    models.SlugField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=300)),
                (
                    "attraction_type",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("summary", models.TextField(blank=True, null=True)),
                ("is_full_record", models.BooleanField(default=False)),
                ("full_description", models.TextField(blank=True, null=True)),
                ("nearest_station", models.TextField(blank=True, null=True)),
                (
                    "website_url",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("admission_info", models.TextField(blank=True, null=True)),
                ("map_url", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "saved_by",
                    models.ManyToManyField(
                        blank=True, related_name="attractions", to="custom_auth.profile"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Outing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("start_notification_sent", models.BooleanField(default=False)),
                (
                    "attraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="attractions.attraction",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="custom_auth.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="SearchTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.TextField(unique=True)),
                ("last_search_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["last_search_date"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="custom_auth.profile",
                    ),
                ),
                (
                    "outing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attractions.outing",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="attraction",
            name="tags",
            field=models.ManyToManyField(blank=True, to="attractions.tag"),
        ),
        migrations.CreateModel(
            name="OutingInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendance_confirmed", models.BooleanField(default=False)),
                ("is_attending", models.BooleanField(default=False)),
                (
                    "invitee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="custom_auth.profile",
                    ),
                ),
                (
                    "outing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attractions.outing",
                    ),
                ),
            ],
            options={
                "unique_together": {("invitee", "outing")},
            },
        ),
    ]
