# Generated by Django 4.1.2 on 2022-10-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.TextField(unique=True)),
                ("last_search", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["last_search"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Attraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=300)),
                (
                    "attraction_type",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("summary", models.TextField(blank=True, null=True)),
                ("is_full_record", models.BooleanField(default=False)),
                ("full_description", models.TextField(blank=True, null=True)),
                ("nearest_station", models.TextField(blank=True, null=True)),
                (
                    "website_url",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("admission_info", models.TextField(blank=True, null=True)),
                ("map_url", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "tags",
                    models.ManyToManyField(blank=True, null=True, to="attractions.tag"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
