# Generated by Django 4.1.2 on 2022-10-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attractions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attraction",
            name="tags",
            field=models.ManyToManyField(blank=True, to="attractions.tag"),
        ),
    ]
