# Generated by Django 4.1.2 on 2022-10-30 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("attractions", "0002_alter_attraction_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attraction",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="attractions", to="attractions.tag"
            ),
        ),
        migrations.CreateModel(
            name="Outing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("start_notification_sent", models.BooleanField(default=False)),
                (
                    "attraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="attractions.attraction",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="OutingInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendance_confirmed", models.BooleanField(default=False)),
                ("is_attending", models.BooleanField(default=False)),
                (
                    "invitee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "outing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="attractions.outing",
                    ),
                ),
            ],
            options={
                "unique_together": {("invitee", "outing")},
            },
        ),
    ]
