# Generated by Django 4.1.2 on 2022-10-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attractions", "0002_alter_attraction_saved_by_alter_attraction_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attraction",
            name="tags",
            field=models.ManyToManyField(
                related_name="attractions", to="attractions.tag"
            ),
        ),
    ]
