# Generated by Django 4.1.2 on 2022-10-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0004_alter_profile_id"),
        ("attractions", "0004_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attraction",
            name="saved_by",
            field=models.ManyToManyField(
                blank=True, related_name="attractions", to="custom_auth.profile"
            ),
        ),
    ]
