# Generated by Django 4.1.2 on 2022-10-30 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0002_profile"),
        ("attractions", "0005_alter_outinginvitation_invitee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attraction",
            name="saved_by",
            field=models.ManyToManyField(
                blank=True, related_name="attractions", to="custom_auth.profile"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="custom_auth.profile"
            ),
        ),
        migrations.AlterField(
            model_name="outing",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="custom_auth.profile"
            ),
        ),
        migrations.AlterField(
            model_name="outinginvitation",
            name="invitee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invites",
                to="custom_auth.profile",
            ),
        ),
    ]
