# Generated by Django 4.1.2 on 2022-10-30 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0004_alter_profile_id"),
        ("attractions", "0005_alter_attraction_saved_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attraction",
            name="saved_by",
            field=models.ManyToManyField(
                blank=True, related_name="saved_attractions", to="custom_auth.profile"
            ),
        ),
        migrations.AlterField(
            model_name="outing",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_outings",
                to="custom_auth.profile",
            ),
        ),
    ]
