# Generated by Django 4.1.2 on 2022-10-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attractions", "0006_attraction_saved_by_alter_comment_creator_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="searchterm",
            options={"ordering": ["last_search_date"]},
        ),
        migrations.RenameField(
            model_name="searchterm",
            old_name="last_search",
            new_name="last_search_date",
        ),
    ]
