# Generated by Django 4.1.2 on 2022-10-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attractions", "0006_alter_attraction_saved_by_alter_outing_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attraction",
            name="uuid",
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
    ]
