# Generated by Django 4.1.2 on 2022-10-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attractions", "0007_alter_attraction_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attraction",
            name="map_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
