# Generated by Django 4.1.2 on 2022-10-31 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attractions", "0008_alter_attraction_map_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(blank=True, verbose_name="Comment"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="outing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="attractions.outing",
            ),
        ),
        migrations.AlterField(
            model_name="outinginvitation",
            name="outing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outing_invites",
                to="attractions.outing",
            ),
        ),
    ]
