# Generated by Django 4.1.2 on 2022-10-31 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attractions", "0009_alter_comment_content_alter_comment_outing_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="outing",
            options={"ordering": ["-start_time"]},
        ),
    ]
